In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
# set paths
project_dir = r"C:\Users\kjdac\OneDrive\Desktop\PORTFOLIO PROJECTS\Health_Insurance_claims_member_engagement"

raw_dir = os.path.join(project_dir, "data_raw")
processed_dir = os.path.join(project_dir, "data_processed")
outputs_dir = os.path.join(project_dir, "outputs")
tables_dir = os.path.join(outputs_dir, "tables")

os.makedirs(processed_dir, exist_ok=True)
os.makedirs(outputs_dir, exist_ok=True)
os.makedirs(tables_dir, exist_ok=True)

print("Project directory:", project_dir)
print("Raw data directory:", raw_dir)
print("Processed data directory:", processed_dir)
print("Outputs directory:", outputs_dir)

Project directory: C:\Users\kjdac\OneDrive\Desktop\PORTFOLIO PROJECTS\Health_Insurance_claims_member_engagement
Raw data directory: C:\Users\kjdac\OneDrive\Desktop\PORTFOLIO PROJECTS\Health_Insurance_claims_member_engagement\data_raw
Processed data directory: C:\Users\kjdac\OneDrive\Desktop\PORTFOLIO PROJECTS\Health_Insurance_claims_member_engagement\data_processed
Outputs directory: C:\Users\kjdac\OneDrive\Desktop\PORTFOLIO PROJECTS\Health_Insurance_claims_member_engagement\outputs

In [3]:
benef_2009_path = os.path.join(raw_dir, "beneficiary_2009", "DE1_0_2009_Beneficiary_Summary_File_Sample_1.csv")
benef_2010_path = os.path.join(raw_dir, "beneficiary_2010", "DE1_0_2010_Beneficiary_Summary_File_Sample_1.csv")
inp_path = os.path.join(raw_dir, "inpatient", "DE1_0_2008_to_2010_Inpatient_Claims_Sample_1.csv")
outp_path = os.path.join(raw_dir, "outpatient", "DE1_0_2008_to_2010_Outpatient_Claims_Sample_1.csv")

print(benef_2009_path)
print(benef_2010_path)
print(inp_path)
print(outp_path)

C:\Users\kjdac\OneDrive\Desktop\PORTFOLIO PROJECTS\Health_Insurance_claims_member_engagement\data_raw\beneficiary_2009\DE1_0_2009_Beneficiary_Summary_File_Sample_1.csv
C:\Users\kjdac\OneDrive\Desktop\PORTFOLIO PROJECTS\Health_Insurance_claims_member_engagement\data_raw\beneficiary_2010\DE1_0_2010_Beneficiary_Summary_File_Sample_1.csv
C:\Users\kjdac\OneDrive\Desktop\PORTFOLIO PROJECTS\Health_Insurance_claims_member_engagement\data_raw\inpatient\DE1_0_2008_to_2010_Inpatient_Claims_Sample_1.csv
C:\Users\kjdac\OneDrive\Desktop\PORTFOLIO PROJECTS\Health_Insurance_claims_member_engagement\data_raw\outpatient\DE1_0_2008_to_2010_Outpatient_Claims_Sample_1.csv

In [4]:
# load files
benef_2009 = pd.read_csv(benef_2009_path, low_memory=False)
benef_2010 = pd.read_csv(benef_2010_path, low_memory=False)
inp = pd.read_csv(inp_path, low_memory=False)
outp = pd.read_csv(outp_path, low_memory=False)

print("benef_2009 shape:", benef_2009.shape)
print("benef_2010 shape:", benef_2010.shape)
print("inpatient shape:", inp.shape)
print("outpatient shape:", outp.shape)

benef_2009 shape: (114538, 32)
benef_2010 shape: (112754, 32)
inpatient shape: (66773, 81)
outpatient shape: (790790, 76)

In [5]:
# preview first few rows
display(benef_2009.head())
display(benef_2010.head())
display(inp.head())
display(outp.head())

,DESYNPUF_ID,BENE_BIRTH_DT,BENE_DEATH_DT,BENE_SEX_IDENT_CD,BENE_RACE_CD,BENE_ESRD_IND,SP_STATE_CODE,BENE_COUNTY_CD,BENE_HI_CVRAGE_TOT_MONS,BENE_SMI_CVRAGE_TOT_MONS,...,SP_STRKETIA,MEDREIMB_IP,BENRES_IP,PPPYMT_IP,MEDREIMB_OP,BENRES_OP,PPPYMT_OP,MEDREIMB_CAR,BENRES_CAR,PPPYMT_CAR
0,00013D2EFD8E45D1,19230501,NaN,1,1,0,26,950,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,100.0,20.0,0.0
1,00016F745862898F,19430101,NaN,1,1,0,39,230,12,12,...,1,36000.0,3204.0,0.0,60.0,70.0,0.0,1350.0,530.0,100.0
2,0001FDD721E223DC,19360901,NaN,2,1,0,39,280,12,12,...,2,0.0,0.0,0.0,30.0,50.0,0.0,20.0,0.0,0.0
3,00021CA6FF03E670,19410601,NaN,1,5,0,6,290,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,90.0,10.0,0.0
4,00024B3D2352D2D0,19360801,NaN,1,1,0,52,590,12,12,...,2,0.0,0.0,0.0,90.0,40.0,0.0,410.0,140.0,0.0

,DESYNPUF_ID,BENE_BIRTH_DT,BENE_DEATH_DT,BENE_SEX_IDENT_CD,BENE_RACE_CD,BENE_ESRD_IND,SP_STATE_CODE,BENE_COUNTY_CD,BENE_HI_CVRAGE_TOT_MONS,BENE_SMI_CVRAGE_TOT_MONS,...,SP_STRKETIA,MEDREIMB_IP,BENRES_IP,PPPYMT_IP,MEDREIMB_OP,BENRES_OP,PPPYMT_OP,MEDREIMB_CAR,BENRES_CAR,PPPYMT_CAR
0,00013D2EFD8E45D1,19230501,NaN,1,1,0,26,950,12,12,...,2,4000.0,1100.0,0.0,0.0,0.0,0.0,90.0,30.0,0.0
1,00016F745862898F,19430101,NaN,1,1,Y,39,230,12,12,...,2,16000.0,1100.0,0.0,0.0,0.0,0.0,930.0,150.0,0.0
2,0001FDD721E223DC,19360901,NaN,2,1,0,39,280,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,00021CA6FF03E670,19410601,NaN,1,5,0,6,290,12,12,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,00024B3D2352D2D0,19360801,NaN,1,1,0,52,590,9,12,...,2,0.0,0.0,0.0,40.0,0.0,0.0,590.0,60.0,0.0

,DESYNPUF_ID,CLM_ID,SEGMENT,CLM_FROM_DT,CLM_THRU_DT,PRVDR_NUM,CLM_PMT_AMT,NCH_PRMRY_PYR_CLM_PD_AMT,AT_PHYSN_NPI,OP_PHYSN_NPI,...,HCPCS_CD_36,HCPCS_CD_37,HCPCS_CD_38,HCPCS_CD_39,HCPCS_CD_40,HCPCS_CD_41,HCPCS_CD_42,HCPCS_CD_43,HCPCS_CD_44,HCPCS_CD_45
0,00013D2EFD8E45D1,196661176988405,1,20100312.0,20100313.0,2600GD,4000.0,0.0,3.139084e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00016F745862898F,196201177000368,1,20090412.0,20090418.0,3900MB,26000.0,0.0,6.476809e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00016F745862898F,196661177015632,1,20090831.0,20090902.0,3900HM,5000.0,0.0,6.119985e+08,6.119985e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00016F745862898F,196091176981058,1,20090917.0,20090920.0,3913XU,5000.0,0.0,4.971603e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00016F745862898F,196261176983265,1,20100626.0,20100701.0,3900MB,16000.0,0.0,6.408400e+09,1.960860e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,DESYNPUF_ID,CLM_ID,SEGMENT,CLM_FROM_DT,CLM_THRU_DT,PRVDR_NUM,CLM_PMT_AMT,NCH_PRMRY_PYR_CLM_PD_AMT,AT_PHYSN_NPI,OP_PHYSN_NPI,...,HCPCS_CD_36,HCPCS_CD_37,HCPCS_CD_38,HCPCS_CD_39,HCPCS_CD_40,HCPCS_CD_41,HCPCS_CD_42,HCPCS_CD_43,HCPCS_CD_44,HCPCS_CD_45
0,00013D2EFD8E45D1,542192281063886,1,20080904.0,20080904.0,2600RA,50.0,0.0,4.824842e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00016F745862898F,542272281166593,1,20090602.0,20090602.0,3901GS,30.0,0.0,2.963420e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00016F745862898F,542282281644416,1,20090623.0,20090623.0,3939PG,30.0,0.0,5.737808e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0001FDD721E223DC,542642281250669,1,20091011.0,20091011.0,3902NU,30.0,0.0,1.233848e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00024B3D2352D2D0,542242281386963,1,20080712.0,20080712.0,5200TV,30.0,0.0,9.688809e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
for name, df in [("benef_2009", benef_2009), ("benef_2010", benef_2010), ("inp", inp), ("outp", outp)]:
    print(f"\n{name} columns:")
    for col in df.columns:
        print(col)

benef_2009 columns:
DESYNPUF_ID
BENE_BIRTH_DT
BENE_DEATH_DT
BENE_SEX_IDENT_CD
BENE_RACE_CD
BENE_ESRD_IND
SP_STATE_CODE
BENE_COUNTY_CD
BENE_HI_CVRAGE_TOT_MONS
BENE_SMI_CVRAGE_TOT_MONS
BENE_HMO_CVRAGE_TOT_MONS
PLAN_CVRG_MOS_NUM
SP_ALZHDMTA
SP_CHF
SP_CHRNKIDN
SP_CNCR
SP_COPD
SP_DEPRESSN
SP_DIABETES
SP_ISCHMCHT
SP_OSTEOPRS
SP_RA_OA
SP_STRKETIA
MEDREIMB_IP
BENRES_IP
PPPYMT_IP
MEDREIMB_OP
BENRES_OP
PPPYMT_OP
MEDREIMB_CAR
BENRES_CAR
PPPYMT_CAR

benef_2010 columns:
DESYNPUF_ID
BENE_BIRTH_DT
BENE_DEATH_DT
BENE_SEX_IDENT_CD
BENE_RACE_CD
BENE_ESRD_IND
SP_STATE_CODE
BENE_COUNTY_CD
BENE_HI_CVRAGE_TOT_MONS
BENE_SMI_CVRAGE_TOT_MONS
BENE_HMO_CVRAGE_TOT_MONS
PLAN_CVRG_MOS_NUM
SP_ALZHDMTA
SP_CHF
SP_CHRNKIDN
SP_CNCR
SP_COPD
SP_DEPRESSN
SP_DIABETES
SP_ISCHMCHT
SP_OSTEOPRS
SP_RA_OA
SP_STRKETIA
MEDREIMB_IP
BENRES_IP
PPPYMT_IP
MEDREIMB_OP
BENRES_OP
PPPYMT_OP
MEDREIMB_CAR
BENRES_CAR
PPPYMT_CAR

inp columns:
DESYNPUF_ID
CLM_ID
SEGMENT
CLM_FROM_DT
CLM_THRU_DT
PRVDR_NUM
CLM_PMT_AMT
NCH_PRMRY_PYR_CLM_PD_AMT
AT_PHYSN_NPI
OP_PHYSN_NPI
OT_PHYSN_NPI
CLM_ADMSN_DT
ADMTNG_ICD9_DGNS_CD
CLM_PASS_THRU_PER_DIEM_AMT
NCH_BENE_IP_DDCTBL_AMT
NCH_BENE_PTA_COINSRNC_LBLTY_AM
NCH_BENE_BLOOD_DDCTBL_LBLTY_AM
CLM_UTLZTN_DAY_CNT
NCH_BENE_DSCHRG_DT
CLM_DRG_CD
ICD9_DGNS_CD_1
ICD9_DGNS_CD_2
ICD9_DGNS_CD_3
ICD9_DGNS_CD_4
ICD9_DGNS_CD_5
ICD9_DGNS_CD_6
ICD9_DGNS_CD_7
ICD9_DGNS_CD_8
ICD9_DGNS_CD_9
ICD9_DGNS_CD_10
ICD9_PRCDR_CD_1
ICD9_PRCDR_CD_2
ICD9_PRCDR_CD_3
ICD9_PRCDR_CD_4
ICD9_PRCDR_CD_5
ICD9_PRCDR_CD_6
HCPCS_CD_1
HCPCS_CD_2
HCPCS_CD_3
HCPCS_CD_4
HCPCS_CD_5
HCPCS_CD_6
HCPCS_CD_7
HCPCS_CD_8
HCPCS_CD_9
HCPCS_CD_10
HCPCS_CD_11
HCPCS_CD_12
HCPCS_CD_13
HCPCS_CD_14
HCPCS_CD_15
HCPCS_CD_16
HCPCS_CD_17
HCPCS_CD_18
HCPCS_CD_19
HCPCS_CD_20
HCPCS_CD_21
HCPCS_CD_22
HCPCS_CD_23
HCPCS_CD_24
HCPCS_CD_25
HCPCS_CD_26
HCPCS_CD_27
HCPCS_CD_28
HCPCS_CD_29
HCPCS_CD_30
HCPCS_CD_31
HCPCS_CD_32
HCPCS_CD_33
HCPCS_CD_34
HCPCS_CD_35
HCPCS_CD_36
HCPCS_CD_37
HCPCS_CD_38
HCPCS_CD_39
HCPCS_CD_40
HCPCS_CD_41
HCPCS_CD_42
HCPCS_CD_43
HCPCS_CD_44
HCPCS_CD_45

outp columns:
DESYNPUF_ID
CLM_ID
SEGMENT
CLM_FROM_DT
CLM_THRU_DT
PRVDR_NUM
CLM_PMT_AMT
NCH_PRMRY_PYR_CLM_PD_AMT
AT_PHYSN_NPI
OP_PHYSN_NPI
OT_PHYSN_NPI
NCH_BENE_BLOOD_DDCTBL_LBLTY_AM
ICD9_DGNS_CD_1
ICD9_DGNS_CD_2
ICD9_DGNS_CD_3
ICD9_DGNS_CD_4
ICD9_DGNS_CD_5
ICD9_DGNS_CD_6
ICD9_DGNS_CD_7
ICD9_DGNS_CD_8
ICD9_DGNS_CD_9
ICD9_DGNS_CD_10
ICD9_PRCDR_CD_1
ICD9_PRCDR_CD_2
ICD9_PRCDR_CD_3
ICD9_PRCDR_CD_4
ICD9_PRCDR_CD_5
ICD9_PRCDR_CD_6
NCH_BENE_PTB_DDCTBL_AMT
NCH_BENE_PTB_COINSRNC_AMT
ADMTNG_ICD9_DGNS_CD
HCPCS_CD_1
HCPCS_CD_2
HCPCS_CD_3
HCPCS_CD_4
HCPCS_CD_5
HCPCS_CD_6
HCPCS_CD_7
HCPCS_CD_8
HCPCS_CD_9
HCPCS_CD_10
HCPCS_CD_11
HCPCS_CD_12
HCPCS_CD_13
HCPCS_CD_14
HCPCS_CD_15
HCPCS_CD_16
HCPCS_CD_17
HCPCS_CD_18
HCPCS_CD_19
HCPCS_CD_20
HCPCS_CD_21
HCPCS_CD_22
HCPCS_CD_23
HCPCS_CD_24
HCPCS_CD_25
HCPCS_CD_26
HCPCS_CD_27
HCPCS_CD_28
HCPCS_CD_29
HCPCS_CD_30
HCPCS_CD_31
HCPCS_CD_32
HCPCS_CD_33
HCPCS_CD_34
HCPCS_CD_35
HCPCS_CD_36
HCPCS_CD_37
HCPCS_CD_38
HCPCS_CD_39
HCPCS_CD_40
HCPCS_CD_41
HCPCS_CD_42
HCPCS_CD_43
HCPCS_CD_44
HCPCS_CD_45

In [7]:
# data quality check
def quick_profile(df, name):
    print(f"\n{name}")
    print("-" * 60)
    print("Shape:", df.shape)
    print("\nTop 10 missing-value counts:")
    print(df.isnull().sum().sort_values(ascending=False).head(10))
    print("\nDuplicate full rows:", df.duplicated().sum())

quick_profile(benef_2009, "Beneficiary 2009")
quick_profile(benef_2010, "Beneficiary 2010")
quick_profile(inp, "Inpatient Claims")
quick_profile(outp, "Outpatient Claims")

Beneficiary 2009
------------------------------------------------------------
Shape: (114538, 32)

Top 10 missing-value counts:
BENE_DEATH_DT               112754
DESYNPUF_ID                      0
BENE_BIRTH_DT                    0
BENE_SEX_IDENT_CD                0
BENE_RACE_CD                     0
BENE_ESRD_IND                    0
SP_STATE_CODE                    0
BENE_COUNTY_CD                   0
BENE_HI_CVRAGE_TOT_MONS          0
BENE_SMI_CVRAGE_TOT_MONS         0
dtype: int64

Duplicate full rows: 0

Beneficiary 2010
------------------------------------------------------------
Shape: (112754, 32)

Top 10 missing-value counts:
BENE_DEATH_DT               110891
DESYNPUF_ID                      0
BENE_BIRTH_DT                    0
BENE_SEX_IDENT_CD                0
BENE_RACE_CD                     0
BENE_ESRD_IND                    0
SP_STATE_CODE                    0
BENE_COUNTY_CD                   0
BENE_HI_CVRAGE_TOT_MONS          0
BENE_SMI_CVRAGE_TOT_MONS         0
dtype: int64

Duplicate full rows: 0

Inpatient Claims
------------------------------------------------------------
Shape: (66773, 81)

Top 10 missing-value counts:
HCPCS_CD_29    66773
HCPCS_CD_30    66773
HCPCS_CD_31    66773
HCPCS_CD_32    66773
HCPCS_CD_1     66773
HCPCS_CD_5     66773
HCPCS_CD_4     66773
HCPCS_CD_3     66773
HCPCS_CD_2     66773
HCPCS_CD_10    66773
dtype: int64

Duplicate full rows: 0

Outpatient Claims
------------------------------------------------------------
Shape: (790790, 76)

Top 10 missing-value counts:
HCPCS_CD_45        790790
ICD9_PRCDR_CD_6    790761
ICD9_PRCDR_CD_5    790755
ICD9_PRCDR_CD_4    790742
ICD9_PRCDR_CD_3    790717
ICD9_PRCDR_CD_2    790667
ICD9_PRCDR_CD_1    790590
ICD9_DGNS_CD_10    789165
HCPCS_CD_44        780234
HCPCS_CD_43        779594
dtype: int64

Duplicate full rows: 0

In [8]:
for name, df in [("benef_2009", benef_2009), ("benef_2010", benef_2010), ("inp", inp), ("outp", outp)]:
    print(f"\n{name}")
    print("rows:", len(df))
    print("unique DESYNPUF_ID:", df["DESYNPUF_ID"].nunique())

benef_2009
rows: 114538
unique DESYNPUF_ID: 114538

benef_2010
rows: 112754
unique DESYNPUF_ID: 112754

inp
rows: 66773
unique DESYNPUF_ID: 37780

outp
rows: 790790
unique DESYNPUF_ID: 85272

In [9]:
with open(os.path.join(tables_dir, "benef_2009_columns.txt"), "w") as f:
    f.write("\n".join(benef_2009.columns))

with open(os.path.join(tables_dir, "benef_2010_columns.txt"), "w") as f:
    f.write("\n".join(benef_2010.columns))

with open(os.path.join(tables_dir, "inpatient_columns.txt"), "w") as f:
    f.write("\n".join(inp.columns))

with open(os.path.join(tables_dir, "outpatient_columns.txt"), "w") as f:
    f.write("\n".join(outp.columns))

In [10]:
# define columns to keep
beneficiary_keep = [
    "DESYNPUF_ID",
    "BENE_BIRTH_DT",
    "BENE_DEATH_DT",
    "BENE_SEX_IDENT_CD",
    "BENE_RACE_CD",
    "BENE_ESRD_IND",
    "SP_STATE_CODE",
    "BENE_COUNTY_CD",
    "BENE_HI_CVRAGE_TOT_MONS",
    "BENE_SMI_CVRAGE_TOT_MONS",
    "BENE_HMO_CVRAGE_TOT_MONS",
    "PLAN_CVRG_MOS_NUM",
    "SP_ALZHDMTA",
    "SP_CHF",
    "SP_CHRNKIDN",
    "SP_CNCR",
    "SP_COPD",
    "SP_DEPRESSN",
    "SP_DIABETES",
    "SP_ISCHMCHT",
    "SP_OSTEOPRS",
    "SP_RA_OA",
    "SP_STRKETIA",
    "MEDREIMB_IP",
    "BENRES_IP",
    "PPPYMT_IP",
    "MEDREIMB_OP",
    "BENRES_OP",
    "PPPYMT_OP",
    "MEDREIMB_CAR",
    "BENRES_CAR",
    "PPPYMT_CAR"
]

inpatient_keep = [
    "DESYNPUF_ID",
    "CLM_ID",
    "SEGMENT",
    "CLM_FROM_DT",
    "CLM_THRU_DT",
    "CLM_ADMSN_DT",
    "NCH_BENE_DSCHRG_DT",
    "PRVDR_NUM",
    "CLM_PMT_AMT",
    "NCH_PRMRY_PYR_CLM_PD_AMT",
    "NCH_BENE_IP_DDCTBL_AMT",
    "NCH_BENE_PTA_COINSRNC_LBLTY_AM",
    "NCH_BENE_BLOOD_DDCTBL_LBLTY_AM",
    "CLM_UTLZTN_DAY_CNT",
    "CLM_DRG_CD",
    "ADMTNG_ICD9_DGNS_CD",
    "ICD9_DGNS_CD_1",
    "ICD9_DGNS_CD_2",
    "ICD9_DGNS_CD_3",
    "ICD9_DGNS_CD_4",
    "ICD9_DGNS_CD_5",
    "ICD9_DGNS_CD_6",
    "ICD9_DGNS_CD_7",
    "ICD9_DGNS_CD_8",
    "ICD9_DGNS_CD_9",
    "ICD9_DGNS_CD_10",
    "ICD9_PRCDR_CD_1",
    "ICD9_PRCDR_CD_2",
    "ICD9_PRCDR_CD_3",
    "ICD9_PRCDR_CD_4",
    "ICD9_PRCDR_CD_5",
    "ICD9_PRCDR_CD_6",
    "HCPCS_CD_1",
    "HCPCS_CD_2",
    "HCPCS_CD_3"
]

outpatient_keep = [
    "DESYNPUF_ID",
    "CLM_ID",
    "SEGMENT",
    "CLM_FROM_DT",
    "CLM_THRU_DT",
    "PRVDR_NUM",
    "CLM_PMT_AMT",
    "NCH_PRMRY_PYR_CLM_PD_AMT",
    "NCH_BENE_BLOOD_DDCTBL_LBLTY_AM",
    "NCH_BENE_PTB_DDCTBL_AMT",
    "NCH_BENE_PTB_COINSRNC_AMT",
    "ADMTNG_ICD9_DGNS_CD",
    "ICD9_DGNS_CD_1",
    "ICD9_DGNS_CD_2",
    "ICD9_DGNS_CD_3",
    "ICD9_DGNS_CD_4",
    "ICD9_DGNS_CD_5",
    "ICD9_DGNS_CD_6",
    "ICD9_DGNS_CD_7",
    "ICD9_DGNS_CD_8",
    "ICD9_DGNS_CD_9",
    "ICD9_DGNS_CD_10",
    "ICD9_PRCDR_CD_1",
    "ICD9_PRCDR_CD_2",
    "ICD9_PRCDR_CD_3",
    "ICD9_PRCDR_CD_4",
    "ICD9_PRCDR_CD_5",
    "ICD9_PRCDR_CD_6",
    "HCPCS_CD_1",
    "HCPCS_CD_2",
    "HCPCS_CD_3"
]

In [11]:
# keep columns that matter
benef_2009_small = benef_2009[beneficiary_keep].copy()
benef_2010_small = benef_2010[beneficiary_keep].copy()
inp_small = inp[inpatient_keep].copy()
outp_small = outp[outpatient_keep].copy()

print("benef_2009_small:", benef_2009_small.shape)
print("benef_2010_small:", benef_2010_small.shape)
print("inp_small:", inp_small.shape)
print("outp_small:", outp_small.shape)

benef_2009_small: (114538, 32)
benef_2010_small: (112754, 32)
inp_small: (66773, 35)
outp_small: (790790, 31)

In [12]:
# convert data columns
benef_date_cols = ["BENE_BIRTH_DT", "BENE_DEATH_DT"]
inp_date_cols = ["CLM_FROM_DT", "CLM_THRU_DT", "CLM_ADMSN_DT", "NCH_BENE_DSCHRG_DT"]
outp_date_cols = ["CLM_FROM_DT", "CLM_THRU_DT"]

for col in benef_date_cols:
    benef_2009_small[col] = pd.to_datetime(benef_2009_small[col], errors="coerce")
    benef_2010_small[col] = pd.to_datetime(benef_2010_small[col], errors="coerce")

for col in inp_date_cols:
    inp_small[col] = pd.to_datetime(inp_small[col], errors="coerce")

for col in outp_date_cols:
    outp_small[col] = pd.to_datetime(outp_small[col], errors="coerce")

In [13]:
# check date conversions
print(benef_2009_small[benef_date_cols].dtypes)
print(benef_2010_small[benef_date_cols].dtypes)
print(inp_small[inp_date_cols].dtypes)
print(outp_small[outp_date_cols].dtypes)

BENE_BIRTH_DT    datetime64[ns]
BENE_DEATH_DT    datetime64[ns]
dtype: object
BENE_BIRTH_DT    datetime64[ns]
BENE_DEATH_DT    datetime64[ns]
dtype: object
CLM_FROM_DT           datetime64[ns]
CLM_THRU_DT           datetime64[ns]
CLM_ADMSN_DT          datetime64[ns]
NCH_BENE_DSCHRG_DT    datetime64[ns]
dtype: object
CLM_FROM_DT    datetime64[ns]
CLM_THRU_DT    datetime64[ns]
dtype: object

In [14]:
# check data types
print("\nBeneficiary 2010 dtypes:")
print(benef_2010_small.dtypes)

print("\nInpatient dtypes:")
print(inp_small.dtypes)

print("\nOutpatient dtypes:")
print(outp_small.dtypes)

Beneficiary 2010 dtypes:
DESYNPUF_ID                         object
BENE_BIRTH_DT               datetime64[ns]
BENE_DEATH_DT               datetime64[ns]
BENE_SEX_IDENT_CD                    int64
BENE_RACE_CD                         int64
BENE_ESRD_IND                       object
SP_STATE_CODE                        int64
BENE_COUNTY_CD                       int64
BENE_HI_CVRAGE_TOT_MONS              int64
BENE_SMI_CVRAGE_TOT_MONS             int64
BENE_HMO_CVRAGE_TOT_MONS             int64
PLAN_CVRG_MOS_NUM                    int64
SP_ALZHDMTA                          int64
SP_CHF                               int64
SP_CHRNKIDN                          int64
SP_CNCR                              int64
SP_COPD                              int64
SP_DEPRESSN                          int64
SP_DIABETES                          int64
SP_ISCHMCHT                          int64
SP_OSTEOPRS                          int64
SP_RA_OA                             int64
SP_STRKETIA                          int64
MEDREIMB_IP                        float64
BENRES_IP                          float64
PPPYMT_IP                          float64
MEDREIMB_OP                        float64
BENRES_OP                          float64
PPPYMT_OP                          float64
MEDREIMB_CAR                       float64
BENRES_CAR                         float64
PPPYMT_CAR                         float64
dtype: object

Inpatient dtypes:
DESYNPUF_ID                               object
CLM_ID                                     int64
SEGMENT                                    int64
CLM_FROM_DT                       datetime64[ns]
CLM_THRU_DT                       datetime64[ns]
CLM_ADMSN_DT                      datetime64[ns]
NCH_BENE_DSCHRG_DT                datetime64[ns]
PRVDR_NUM                                 object
CLM_PMT_AMT                              float64
NCH_PRMRY_PYR_CLM_PD_AMT                 float64
NCH_BENE_IP_DDCTBL_AMT                   float64
NCH_BENE_PTA_COINSRNC_LBLTY_AM           float64
NCH_BENE_BLOOD_DDCTBL_LBLTY_AM           float64
CLM_UTLZTN_DAY_CNT                       float64
CLM_DRG_CD                                object
ADMTNG_ICD9_DGNS_CD                       object
ICD9_DGNS_CD_1                            object
ICD9_DGNS_CD_2                            object
ICD9_DGNS_CD_3                            object
ICD9_DGNS_CD_4                            object
ICD9_DGNS_CD_5                            object
ICD9_DGNS_CD_6                            object
ICD9_DGNS_CD_7                            object
ICD9_DGNS_CD_8                            object
ICD9_DGNS_CD_9                            object
ICD9_DGNS_CD_10                           object
ICD9_PRCDR_CD_1                          float64
ICD9_PRCDR_CD_2                           object
ICD9_PRCDR_CD_3                           object
ICD9_PRCDR_CD_4                           object
ICD9_PRCDR_CD_5                           object
ICD9_PRCDR_CD_6                           object
HCPCS_CD_1                               float64
HCPCS_CD_2                               float64
HCPCS_CD_3                               float64
dtype: object

Outpatient dtypes:
DESYNPUF_ID                               object
CLM_ID                                     int64
SEGMENT                                    int64
CLM_FROM_DT                       datetime64[ns]
CLM_THRU_DT                       datetime64[ns]
PRVDR_NUM                                 object
CLM_PMT_AMT                              float64
NCH_PRMRY_PYR_CLM_PD_AMT                 float64
NCH_BENE_BLOOD_DDCTBL_LBLTY_AM           float64
NCH_BENE_PTB_DDCTBL_AMT                  float64
NCH_BENE_PTB_COINSRNC_AMT                float64
ADMTNG_ICD9_DGNS_CD                       object
ICD9_DGNS_CD_1                            object
ICD9_DGNS_CD_2                            object
ICD9_DGNS_CD_3                            object
ICD9_DGNS_CD_4                            object
ICD9_DGNS_CD_5                            object
ICD9_DGNS_CD_6                            object
ICD9_DGNS_CD_7                            object
ICD9_DGNS_CD_8                            object
ICD9_DGNS_CD_9                            object
ICD9_DGNS_CD_10                           object
ICD9_PRCDR_CD_1                          float64
ICD9_PRCDR_CD_2                           object
ICD9_PRCDR_CD_3                           object
ICD9_PRCDR_CD_4                           object
ICD9_PRCDR_CD_5                           object
ICD9_PRCDR_CD_6                           object
HCPCS_CD_1                                object
HCPCS_CD_2                                object
HCPCS_CD_3                                object
dtype: object

In [15]:
# create data dictionary
data_dict_rows = [
    ["beneficiary", "DESYNPUF_ID", "Unique member identifier", "Join key"],
    ["beneficiary", "BENE_BIRTH_DT", "Member birth date", "Age feature"],
    ["beneficiary", "BENE_DEATH_DT", "Member death date if present", "Outcome / status feature"],
    ["beneficiary", "BENE_SEX_IDENT_CD", "Member sex code", "Demographic feature"],
    ["beneficiary", "BENE_RACE_CD", "Member race code", "Demographic feature"],
    ["beneficiary", "BENE_ESRD_IND", "End-stage renal disease indicator", "Clinical risk feature"],
    ["beneficiary", "SP_DIABETES", "Diabetes indicator", "Chronic condition feature"],
    ["beneficiary", "SP_CHF", "Congestive heart failure indicator", "Chronic condition feature"],
    ["beneficiary", "SP_COPD", "COPD indicator", "Chronic condition feature"],
    ["beneficiary", "MEDREIMB_IP", "Medicare inpatient reimbursement", "Historical cost feature"],
    ["beneficiary", "MEDREIMB_OP", "Medicare outpatient reimbursement", "Historical cost feature"],
    ["inpatient", "CLM_ID", "Claim identifier", "Claim-level tracking"],
    ["inpatient", "CLM_FROM_DT", "Claim start date", "Timeline feature"],
    ["inpatient", "CLM_THRU_DT", "Claim end date", "Timeline feature"],
    ["inpatient", "CLM_PMT_AMT", "Claim payment amount", "Cost feature"],
    ["inpatient", "CLM_UTLZTN_DAY_CNT", "Utilization day count", "Utilization feature"],
    ["inpatient", "ICD9_DGNS_CD_1", "Primary diagnosis code", "Clinical context"],
    ["outpatient", "CLM_ID", "Claim identifier", "Claim-level tracking"],
    ["outpatient", "CLM_FROM_DT", "Claim start date", "Timeline feature"],
    ["outpatient", "CLM_PMT_AMT", "Claim payment amount", "Cost feature"],
    ["outpatient", "ICD9_DGNS_CD_1", "Primary diagnosis code", "Clinical context"],
    ["outpatient", "HCPCS_CD_1", "Primary service/procedure code", "Service context"]
]

data_dict = pd.DataFrame(
    data_dict_rows,
    columns=["table_name", "column_name", "business_meaning", "use_in_project"]
)

data_dict

,table_name,column_name,business_meaning,use_in_project
0,beneficiary,DESYNPUF_ID,Unique member identifier,Join key
1,beneficiary,BENE_BIRTH_DT,Member birth date,Age feature
2,beneficiary,BENE_DEATH_DT,Member death date if present,Outcome / status feature
3,beneficiary,BENE_SEX_IDENT_CD,Member sex code,Demographic feature
4,beneficiary,BENE_RACE_CD,Member race code,Demographic feature
5,beneficiary,BENE_ESRD_IND,End-stage renal disease indicator,Clinical risk feature
6,beneficiary,SP_DIABETES,Diabetes indicator,Chronic condition feature
7,beneficiary,SP_CHF,Congestive heart failure indicator,Chronic condition feature
8,beneficiary,SP_COPD,COPD indicator,Chronic condition feature
9,beneficiary,MEDREIMB_IP,Medicare inpatient reimbursement,Historical cost feature
10,beneficiary,MEDREIMB_OP,Medicare outpatient reimbursement,Historical cost feature
11,inpatient,CLM_ID,Claim identifier,Claim-level tracking
12,inpatient,CLM_FROM_DT,Claim start date,Timeline feature
13,inpatient,CLM_THRU_DT,Claim end date,Timeline feature
14,inpatient,CLM_PMT_AMT,Claim payment amount,Cost feature
15,inpatient,CLM_UTLZTN_DAY_CNT,Utilization day count,Utilization feature
16,inpatient,ICD9_DGNS_CD_1,Primary diagnosis code,Clinical context
17,outpatient,CLM_ID,Claim identifier,Claim-level tracking
18,outpatient,CLM_FROM_DT,Claim start date,Timeline feature
19,outpatient,CLM_PMT_AMT,Claim payment amount,Cost feature
20,outpatient,ICD9_DGNS_CD_1,Primary diagnosis code,Clinical context
21,outpatient,HCPCS_CD_1,Primary service/procedure code,Service context

In [16]:
benef_2009_small.to_csv(os.path.join(processed_dir, "benef_2009_small.csv"), index=False)
benef_2010_small.to_csv(os.path.join(processed_dir, "benef_2010_small.csv"), index=False)
inp_small.to_csv(os.path.join(processed_dir, "inpatient_small.csv"), index=False)
outp_small.to_csv(os.path.join(processed_dir, "outpatient_small.csv"), index=False)
data_dict.to_csv(os.path.join(processed_dir, "project_data_dictionary.csv"), index=False)

print("Files saved to:", processed_dir)
print(os.listdir(processed_dir))

Files saved to: C:\Users\kjdac\OneDrive\Desktop\PORTFOLIO PROJECTS\Health_Insurance_claims_member_engagement\data_processed
['benef_2009_small.csv', 'benef_2010_small.csv', 'inpatient_small.csv', 'outpatient_small.csv', 'project_data_dictionary.csv']

In [17]:
# sanity check
benef_2010_check = pd.read_csv(os.path.join(processed_dir, "benef_2010_small.csv"), low_memory=False)
inp_check = pd.read_csv(os.path.join(processed_dir, "inpatient_small.csv"), low_memory=False)
outp_check = pd.read_csv(os.path.join(processed_dir, "outpatient_small.csv"), low_memory=False)

print("benef_2010_check:", benef_2010_check.shape)
print("inp_check:", inp_check.shape)
print("outp_check:", outp_check.shape)

benef_2010_check: (112754, 32)
inp_check: (66773, 35)
outp_check: (790790, 31)